spring:
  application:
    name: accounting
  datasource:
    url: jdbc:mysql://localhost:3306/accounting?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
